
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: backend_api_development
  username: postgres
  password: 1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: backend_api_test
  username: postgres
  password: 1234
  host: localhost
  
  port: 5432



production:
  primary: &primary_production
    <<: *default
    database: backend_api_production
    username: backend_api
    password: <%= ENV["BACKEND_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: backend_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_api_production_cable
    migrations_paths: db/cable_migrate
